'use strict';var $jscomp={scope:{},global:this},Symbol;$jscomp.initSymbol=function(){$jscomp.global.Symbol||(Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();Symbol.iterator||(Symbol.iterator=Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[Symbol.iterator])return a[Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};
var module$cursor={},Cursor$$module$cursor=function(a,b,c){c=void 0===c?FG$$module$cursor:c;this.row_=void 0===a?0:a;this.column_=void 0===b?0:b;this.flags_=c;this.stack_=[]};Cursor$$module$cursor.prototype.save=function(a){(a=void 0===a?null:a)||(a=[this.row_,this.column_,this.flags_]);this.stack_.push.apply(this.stack_,[].concat($jscomp.arrayFromIterable(a)))};
Cursor$$module$cursor.prototype.restore=function(){var a=[this.flags_,this.column_,this.row_];this.flags_=this.stack_.pop();this.column_=this.stack_.pop();this.row_=this.stack_.pop();return a};Cursor$$module$cursor.prototype.clone=function(){var a=new Cursor$$module$cursor(this.row_,this.column_,this.flags_);Array.prototype.push.apply(a.stack_,this.stack_);return a};Cursor$$module$cursor.prototype.updateCursor=function(a,b){};
Object.defineProperties(Cursor$$module$cursor.prototype,{r:{configurable:!0,enumerable:!0,get:function(){return this.row_},set:function(a){this.row_=Math.max(1,a);this.updateCursor(this.row_,this.column_)}},c:{configurable:!0,enumerable:!0,get:function(){return this.column_},set:function(a){this.column_=Math.max(1,a);this.updateCursor(this.row_,this.column_)}},flags:{configurable:!0,enumerable:!0,get:function(){return this.flags_},set:function(a){this.flags_=a&2047}},b:{configurable:!0,enumerable:!0,
get:function(){return!!(this.flags_&BOLD$$module$cursor)},set:function(a){this.flags_=a?this.flags_|BOLD$$module$cursor:this.flags_&~BOLD$$module$cursor}},i:{configurable:!0,enumerable:!0,get:function(){return!!(this.flags_&ITALIC$$module$cursor)},set:function(a){this.flags_=a?this.flags_|ITALIC$$module$cursor:this.flags_&~ITALIC$$module$cursor}},u:{configurable:!0,enumerable:!0,get:function(){return!!(this.flags_&UNDERLINE$$module$cursor)},set:function(a){this.flags_=a?this.flags_|UNDERLINE$$module$cursor:
this.flags_&~UNDERLINE$$module$cursor}},bl:{configurable:!0,enumerable:!0,get:function(){return!!(this.flags_&BLINK$$module$cursor)},set:function(a){this.flags_=a?this.flags_|BLINK$$module$cursor:this.flags_&~BLINK$$module$cursor}},rev:{configurable:!0,enumerable:!0,get:function(){return!!(this.flags_&REVERSE$$module$cursor)},set:function(a){this.flags_=a?this.flags_|REVERSE$$module$cursor:this.flags_&~REVERSE$$module$cursor}},fg:{configurable:!0,enumerable:!0,get:function(){return this.flags_&FG$$module$cursor},
set:function(a){this.flags_=this.flags_&~FG$$module$cursor|a&FG$$module$cursor}},bg:{configurable:!0,enumerable:!0,get:function(){return(this.flags_&BG$$module$cursor)>>>3},set:function(a){this.flags_=this.flags_&~BG$$module$cursor|(a&FG$$module$cursor)<<3}}});var FG$$module$cursor=7,BG$$module$cursor=56,BOLD$$module$cursor=64,ITALIC$$module$cursor=128,UNDERLINE$$module$cursor=256,BLINK$$module$cursor=512,REVERSE$$module$cursor=1024;Cursor$$module$cursor.FG=FG$$module$cursor;
Cursor$$module$cursor.BG=BG$$module$cursor;Cursor$$module$cursor.BOLD=BOLD$$module$cursor;Cursor$$module$cursor.ITALIC=ITALIC$$module$cursor;Cursor$$module$cursor.UNDERLINE=UNDERLINE$$module$cursor;Cursor$$module$cursor.BLINK=BLINK$$module$cursor;Cursor$$module$cursor.REVERSE=REVERSE$$module$cursor;module$cursor.default=Cursor$$module$cursor;var module$state={},State$$module$state=function(a,b,c,d){module$cursor.default.call(this,void 0===b?0:b,void 0===c?0:c,void 0===d?7:d);this.grid_=getOrAdd$$module$state(a,"grid");this.cursor_=getOrAdd$$module$state(a,"cursor");this.data_=[];this.rows_=[];this.playing_=!0};$jscomp.inherits(State$$module$state,module$cursor.default);State$$module$state.REVERSE=module$cursor.default.REVERSE;State$$module$state.BLINK=module$cursor.default.BLINK;State$$module$state.UNDERLINE=module$cursor.default.UNDERLINE;
State$$module$state.ITALIC=module$cursor.default.ITALIC;State$$module$state.BOLD=module$cursor.default.BOLD;State$$module$state.BG=module$cursor.default.BG;State$$module$state.FG=module$cursor.default.FG;
State$$module$state.prototype.clear=function(a,b){a=void 0===a?null:a;b=void 0===b?null:b;null==a&&(a=[0,this.data_.length]);if(a instanceof Array){if(null!=b)throw Error("cols is ignored if rows is array.");1==a.length&&(a=[a[0],this.data_.length]);if(a[1]<=a[0])return[];var c=a[1]-a[0],d=[];d.length=c;for(var e=0;e<c;e++)d[e]=[];for(;this.data_.length<a[0];)this.data_.push([]);for(d=this.data_.splice.apply(this.data_,[].concat([a[0],c],$jscomp.arrayFromIterable(d)));d.size<c;)d.push([]);if(this.playing_)for(e=
$jscomp.makeIterator(this.rows_.slice(a[0],a[1])),c=e.next();!c.done;c=e.next())for(var f=$jscomp.makeIterator(c.value),c=f.next();!c.done;c=f.next())c.value.style.display="none";return d}c=getOrEmpty$$module$state(this.data_,Number(a));null==b&&(b=[0,c.length]);b instanceof Array||(b=[b,b+1]);1==b.length&&(b=[b[0],c.length/2]);if(b[1]<=b[0])return[[]];d=b[1]-b[0];e=[];c.length>2*b[1]&&(e.length=2*d);e=c.splice.apply(c,[].concat([2*b[0],2*d],$jscomp.arrayFromIterable(e)));e.size=2*d;if(this.playing_)for(d=
$jscomp.makeIterator((this.rows_[a]||[]).slice(b[0],b[1])),c=d.next();!c.done;c=d.next())c.value.style.display="none";return[e]};
State$$module$state.prototype.write=function(a,b,c){b=void 0===b?null:b;c=void 0===c?null:c;1==arguments.length&&(b=this.r,c=this.c,this.c+=a.length);var d=getOrEmpty$$module$state(this.data_,b),e=void 0;d.length<2*c&&(d.length=2*c);if(a instanceof Array)e=d.splice.apply(d,[].concat([2*c,a.length],$jscomp.arrayFromIterable(a))),e.length=a.length;else{e=d.slice(2*c,2*(c+a.length));e.length=2*a.length;for(var f=0;f<a.length;f++)d[2*(c+f)]=a[f],d[2*(c+f)+1]=this.flags}if(this.playing_)for(var f=this.cells_(b,
c,e.length/2),h=c;h<c+e.length/2;h++)setCell$$module$state(f[h-c],d[2*h],d[2*h+1]);return e};State$$module$state.prototype.pause=function(){this.playing_=!1};
State$$module$state.prototype.play=function(){this.rows_.length<this.data_.length&&this.cells_(this.data_.length-1,0,1);for(var a=0;a<this.rows_.length;a++){var b=this.data_[a]||[],c=this.rows_[a];c.length<b.length&&this.cells_(a,0,b.length);for(var d=0;d<c.length;d++){var e=c[d];b[2*d]?setCell$$module$state(e,b[2*d],b[2*d+1]):e.style.display="none"}}this.playing_=!0};
State$$module$state.prototype.cells_=function(a,b,c){for(;this.rows_.length<=a;){var d=document.createElement("div");d.style.left="0";d.style.top=17*this.rows_.length+1+"px";d.style.display="none";this.grid_.appendChild(d);this.rows_.push([d])}for(var d=this.rows_[a],e=this.rows_.length>a+1?this.rows_[a+1][0]:null;d.length<b+c;){var f=document.createElement("div");f.style.left=8*d.length+"px";f.style.top=17*a+1+"px";f.style.display="none";this.grid_.insertBefore(f,e);d.push(f)}return d.slice(b,b+
c)};State$$module$state.prototype.updateCursor=function(a,b){this.cursor_&&(this.cursor_.style.top=17*a+1+"px",this.cursor_.style.left=8*b+"px")};function getOrAdd$$module$state(a,b){var c=a.querySelector("."+b);c||(c=document.createElement("div"),c.classList.add(b),a.appendChild(c));return c}function getOrEmpty$$module$state(a,b){for(;a.length<=b;)a.push([]);return a[b]}
function setCell$$module$state(a,b,c){a.style.display="block";b&&1<b.length&&(b=b.substring(0,1));a.textContent=b?String(b):" ";c=c?Number(c):0;a.className="";c&module$cursor.default.BOLD&&a.classList.add("b");c&module$cursor.default.ITALIC&&a.classList.add("i");c&module$cursor.default.UNDERLINE&&a.classList.add("u");c&module$cursor.default.BLINK&&a.classList.add("bl");c&module$cursor.default.REVERSE&&a.classList.add("rev");a.classList.add("fg"+(c&module$cursor.default.FG));a.classList.add("bg"+(c>>>
3&module$cursor.default.FG))}module$state.default=State$$module$state;var module$reader={},Reader$$module$reader=function(){this.views_=[];this.lastPos_=this.pos_=this.index_=0};Reader$$module$reader.prototype.next=function(){var a=this.currentView_();return a?a.getUint8(this.pos_++):-1};Reader$$module$reader.prototype.peek=function(){var a=this.currentView_();return a?a.getUint8(this.pos_):-1};Reader$$module$reader.prototype.nextChar=function(){var a=this.nextCodepoint();return 0>a?"":String.fromCodePoint(a)};
Reader$$module$reader.prototype.nextCodepoint=function(){var a=this.next();if(0>a)return a;for(var b=128,c=0;a&b;)a&=~b,b>>=1,c++;for(;1<c--;){b=this.next();if(0>b)return b;a=(a<<6)+(b&63)}return a};Reader$$module$reader.prototype.readDigits=function(){for(var a=function(a){return 48<=a&&57>=a},b=null;a(this.peek());)b=10*b+(this.next()-48);return null==b?-1:b};
Reader$$module$reader.prototype.readNumbers=function(){for(var a=[];;){var b=this.readDigits();if(0>b)return a.length&&console.log("trailing semicolon"),a;a.push(b);if(59==this.peek())this.next();else return a}};Reader$$module$reader.prototype.currentView_=function(){for(;this.index_<this.views_.length;){var a=this.views_[this.index_];if(this.pos_<a.byteLength)return a;this.pos_=0;this.index_++}return null};Reader$$module$reader.prototype.eof=function(){return null!=this.currentView_()};
Reader$$module$reader.prototype.add=function(a){this.views_.push(a)};Reader$$module$reader.prototype.save=function(){this.lastPos_=this.pos_;0<this.index_&&(this.views_.splice(0,this.index_),this.index_=0)};Reader$$module$reader.prototype.backtrack=function(){this.pos_=this.lastPos_;this.index_=0};module$reader.default=Reader$$module$reader;var module$command={},Command$$module$command=function(){};Command$$module$command.prototype.apply=function(a){throw new AbstractMethod$$module$command;};Command$$module$command.prototype.undo=function(a){throw new AbstractMethod$$module$command;};
Command$$module$command.parse=function(a){for(var b=[];;){a.save();var c=a.nextCodepoint();if(32<=c)b.push(String.fromCharCode(c));else{if(0>c||b.length)return a.backtrack(),b.length?new Characters$$module$command(b.join("")):null;if(27==c){b=a.nextCodepoint();if(91==b)return BracketPrefix$$module$command.parse(a);if(55==b)return new SaveCursor$$module$command;if(56==b)return new RestoreCursor$$module$command;if(0>b)return a.backtrack(),null;console.log("Bad escape: 0x1b 0x"+b.toString(16));a.backtrack();
a.next();return new UnknownCommand$$module$command("\u001b","\\e\\x"+b.toString(16))}if(10==c)return new LineFeed$$module$command;if(13==c)return new CarriageReturn$$module$command;if(8==c)return new Backspace$$module$command;console.log("Unknown non-printing char: "+c);return new UnknownCommand$$module$command(String.fromCharCode(c),"\\x"+c.toString(16))}}};
Object.defineProperties(Command$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){throw new AbstractMethod$$module$command;}},keyframe:{configurable:!0,enumerable:!0,get:function(){return!1}}});var IgnoredCommand$$module$command=function(a){Command$$module$command.call(this);this.ansi_=a};$jscomp.inherits(IgnoredCommand$$module$command,Command$$module$command);IgnoredCommand$$module$command.parse=Command$$module$command.parse;
IgnoredCommand$$module$command.prototype.apply=function(a){};IgnoredCommand$$module$command.prototype.undo=function(a){};IgnoredCommand$$module$command.prototype.toString=function(){return"IgnoredCommand{"+this.ansi_.replace("\u001b","\\e")+"}"};Object.defineProperties(IgnoredCommand$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return this.ansi_}}});var UnknownCommand$$module$command=function(a,b){IgnoredCommand$$module$command.call(this,a);console.log(b)};
$jscomp.inherits(UnknownCommand$$module$command,IgnoredCommand$$module$command);UnknownCommand$$module$command.parse=IgnoredCommand$$module$command.parse;UnknownCommand$$module$command.prototype.toString=function(){return IgnoredCommand$$module$command.prototype.toString.call(this).replace("Ignored","Unknown")};var Characters$$module$command=function(a){Command$$module$command.call(this);this.chars_=a;this.undo_=[]};$jscomp.inherits(Characters$$module$command,Command$$module$command);
Characters$$module$command.parse=Command$$module$command.parse;Characters$$module$command.prototype.apply=function(a){this.undo_=a.write(this.chars_)};Characters$$module$command.prototype.undo=function(a){a.c-=this.chars_.length;a.write(this.undo_,a.r,a.c)};Characters$$module$command.prototype.toString=function(){return"Characters{"+this.chars_+"}"};Object.defineProperties(Characters$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return this.chars_}}});
var BracketPrefix$$module$command=function(a){Command$$module$command.apply(this,arguments)};$jscomp.inherits(BracketPrefix$$module$command,Command$$module$command);BracketPrefix$$module$command.prototype.params=function(){return[]};BracketPrefix$$module$command.prototype.suffix=function(){throw new AbstractMethod$$module$command;};
BracketPrefix$$module$command.parse=function(a){var b=a.readNumbers(),c=a.nextChar();return c?"?"==c?(c=a.readNumbers(),a=a.nextChar(),b="e["+b.join(";")+"?"+c.join(";")+a,"h"==a||"l"==a?new IgnoredCommand$$module$command(b):new UnknownCommand$$module$command(b,"Expected h or l after \\e[?#")):"H"==c||"f"==c?new CursorPosition$$module$command(b[0]||0,b[1]||0):"A"==c?new CursorUp$$module$command(b[0]||1):"B"==c?new CursorDown$$module$command(b[0]||1):"C"==c?new CursorForward$$module$command(b[0]||
1):"D"==c?new CursorBackward$$module$command(b[0]||1):"J"==c?2==b[0]?new EraseDisplayFull$$module$command:1==b[0]?new EraseDisplayStart$$module$command:new EraseDisplayEnd$$module$command:"K"==c?2==b[0]?new EraseInLineFull$$module$command:1==b[0]?new EraseInLineStart$$module$command:new EraseInLineEnd$$module$command:"m"==c?new CharAttrs$$module$command(b):new UnknownCommand$$module$command("e["+b.join(";")+c,"unknown"):(a.backtrack(),null)};
Object.defineProperties(BracketPrefix$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\u001b["+this.params().join(";")+this.suffix()}}});var CursorPosition$$module$command=function(a,b){this.r_=u16$$module$command(a);this.c_=u16$$module$command(b);this.undo_=null};$jscomp.inherits(CursorPosition$$module$command,BracketPrefix$$module$command);CursorPosition$$module$command.parse=BracketPrefix$$module$command.parse;
CursorPosition$$module$command.prototype.params=function(){return[this.r_,this.c_]};CursorPosition$$module$command.prototype.suffix=function(){return"H"};CursorPosition$$module$command.prototype.apply=function(a){this.undo_=[a.r,a.c];a.r=this.r_;a.c=this.c_};CursorPosition$$module$command.prototype.undo=function(a){a.r=this.undo_[0];a.c=this.undo_[1]};CursorPosition$$module$command.prototype.toString=function(){return"CursorPosition{"+this.r_+", "+this.c_+"}"};var LineFeed$$module$command=function(){Command$$module$command.call(this)};
$jscomp.inherits(LineFeed$$module$command,Command$$module$command);LineFeed$$module$command.parse=Command$$module$command.parse;LineFeed$$module$command.prototype.apply=function(a){a.r++};LineFeed$$module$command.prototype.undo=function(a){a.r--};LineFeed$$module$command.prototype.toString=function(){return"LineFeed"};Object.defineProperties(LineFeed$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\n"}}});
var CarriageReturn$$module$command=function(){Command$$module$command.call(this);this.undo_=0};$jscomp.inherits(CarriageReturn$$module$command,Command$$module$command);CarriageReturn$$module$command.parse=Command$$module$command.parse;CarriageReturn$$module$command.prototype.apply=function(a){this.undo_=a.c;a.c=0};CarriageReturn$$module$command.prototype.undo=function(a){a.c=this.undo_};CarriageReturn$$module$command.prototype.toString=function(){return"CarriageReturn"};
Object.defineProperties(CarriageReturn$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\r"}}});var Backspace$$module$command=function(){Command$$module$command.call(this)};$jscomp.inherits(Backspace$$module$command,Command$$module$command);Backspace$$module$command.parse=Command$$module$command.parse;Backspace$$module$command.prototype.apply=function(a){a.c--};Backspace$$module$command.prototype.undo=function(a){a.c++};
Backspace$$module$command.prototype.toString=function(){return"Backspace"};Object.defineProperties(Backspace$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\b"}}});var CursorRelative$$module$command=function(a){BracketPrefix$$module$command.call(this);this.count_=u16$$module$command(a)};$jscomp.inherits(CursorRelative$$module$command,BracketPrefix$$module$command);CursorRelative$$module$command.parse=BracketPrefix$$module$command.parse;
CursorRelative$$module$command.prototype.params=function(){return 1!=this.count_?[this.count_]:[]};CursorRelative$$module$command.prototype.apply=function(a){this.applyInternal(a,this.count_)};CursorRelative$$module$command.prototype.undo=function(a){this.applyInternal(a,-this.count_)};CursorRelative$$module$command.prototype.applyInternal=function(a,b){throw new AbstractMethod$$module$command;};
Object.defineProperties(CursorRelative$$module$command.prototype,{count:{configurable:!0,enumerable:!0,get:function(){return this.count_}}});var CursorUp$$module$command=function(a){CursorRelative$$module$command.call(this,a)};$jscomp.inherits(CursorUp$$module$command,CursorRelative$$module$command);CursorUp$$module$command.parse=CursorRelative$$module$command.parse;CursorUp$$module$command.prototype.suffix=function(){return"A"};
CursorUp$$module$command.prototype.applyInternal=function(a,b){a.r-=b};CursorUp$$module$command.prototype.toString=function(){return"CursorUp{"+this.count+"}"};var CursorDown$$module$command=function(a){CursorRelative$$module$command.call(this,a)};$jscomp.inherits(CursorDown$$module$command,CursorRelative$$module$command);CursorDown$$module$command.parse=CursorRelative$$module$command.parse;CursorDown$$module$command.prototype.suffix=function(){return"B"};
CursorDown$$module$command.prototype.applyInternal=function(a,b){a.r+=b};CursorDown$$module$command.prototype.toString=function(){return"CursorDown{"+this.count+"}"};var CursorBackward$$module$command=function(a){CursorRelative$$module$command.call(this,a)};$jscomp.inherits(CursorBackward$$module$command,CursorRelative$$module$command);CursorBackward$$module$command.parse=CursorRelative$$module$command.parse;CursorBackward$$module$command.prototype.suffix=function(){return"C"};
CursorBackward$$module$command.prototype.applyInternal=function(a,b){a.c-=b};CursorBackward$$module$command.prototype.toString=function(){return"CursorBackward{"+this.count+"}"};var CursorForward$$module$command=function(a){CursorRelative$$module$command.call(this,a)};$jscomp.inherits(CursorForward$$module$command,CursorRelative$$module$command);CursorForward$$module$command.parse=CursorRelative$$module$command.parse;CursorForward$$module$command.prototype.suffix=function(){return"D"};
CursorForward$$module$command.prototype.applyInternal=function(a,b){a.c+=b};CursorForward$$module$command.prototype.toString=function(){return"CursorForward{"+this.count+"}"};
var CharAttrs$$module$command=function(a){function b(a,b){a==module$state.default.BG&&(b<<=3);c|=b;d&=~a}BracketPrefix$$module$command.call(this);this.args_=a.map(u16$$module$command);for(var c=0,d=65535,e=0;e<a.length;e++){var f=this.args_[e];1==f?c|=module$state.default.BOLD:3==f?c|=module$state.default.ITALIC:4==f?c|=module$state.default.UNDERLINE:5==f?c|=module$state.default.BLINK:7==f?c|=module$state.default.REVERSE:30<=f&&37>=f?b(module$state.default.FG,f-30):40<=f&&47>=f?b(module$state.default.BG,
f-40):38==f&&5==this.args_[e+1]?b(module$state.default.FG,this.args_[e+=2]):48==f&&5==this.args_[e+1]&&b(module$state.default.BG,this.args_[e+=2])}this.mask_=c?c<<16|d:module$state.default.FG<<16;this.undo_=0};$jscomp.inherits(CharAttrs$$module$command,BracketPrefix$$module$command);CharAttrs$$module$command.parse=BracketPrefix$$module$command.parse;CharAttrs$$module$command.prototype.params=function(){return this.args_};
CharAttrs$$module$command.prototype.apply=function(a){this.undo_=a.flags;a.flags=a.flags&this.mask_|this.mask_>>>16};CharAttrs$$module$command.prototype.undo=function(a){a.flags=this.undo_};CharAttrs$$module$command.prototype.toString=function(){return"CharsAttr{"+this.args_.join(";")+" => 0x"+this.mask_.toString(16)+"}"};var SaveCursor$$module$command=function(){Command$$module$command.call(this)};$jscomp.inherits(SaveCursor$$module$command,Command$$module$command);
SaveCursor$$module$command.parse=Command$$module$command.parse;SaveCursor$$module$command.prototype.apply=function(a){a.save()};SaveCursor$$module$command.prototype.undo=function(a){a.restore()};SaveCursor$$module$command.prototype.toString=function(){return"SaveCursor"};Object.defineProperties(SaveCursor$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\u001b7"}}});var RestoreCursor$$module$command=function(){Command$$module$command.call(this);this.undo_=[]};
$jscomp.inherits(RestoreCursor$$module$command,Command$$module$command);RestoreCursor$$module$command.parse=Command$$module$command.parse;RestoreCursor$$module$command.prototype.apply=function(a){this.undo_=a.restore()};RestoreCursor$$module$command.prototype.undo=function(a){a.save(this.undo_)};RestoreCursor$$module$command.prototype.toString=function(){return"RestoreCursor"};Object.defineProperties(RestoreCursor$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\u001b8"}}});
var Delete$$module$command=function(){Command$$module$command.call(this);this.undo_=[]};$jscomp.inherits(Delete$$module$command,Command$$module$command);Delete$$module$command.parse=Command$$module$command.parse;Delete$$module$command.prototype.apply=function(a){a.c--;this.undo_=a.clear(a.r,a.c)[0]};Delete$$module$command.prototype.undo=function(a){a.write(this.undo_)};Delete$$module$command.prototype.toString=function(){return"Delete"};
Object.defineProperties(Delete$$module$command.prototype,{ansi:{configurable:!0,enumerable:!0,get:function(){return"\u007f"}}});var EraseDisplay$$module$command=function(){BracketPrefix$$module$command.call(this);this.erased=[]};$jscomp.inherits(EraseDisplay$$module$command,BracketPrefix$$module$command);EraseDisplay$$module$command.parse=BracketPrefix$$module$command.parse;EraseDisplay$$module$command.prototype.suffix=function(){return"J"};var EraseDisplayFull$$module$command=function(){EraseDisplay$$module$command.call(this)};
$jscomp.inherits(EraseDisplayFull$$module$command,EraseDisplay$$module$command);EraseDisplayFull$$module$command.parse=EraseDisplay$$module$command.parse;EraseDisplayFull$$module$command.prototype.params=function(){return[2]};EraseDisplayFull$$module$command.prototype.apply=function(a){this.erased=a.clear()};EraseDisplayFull$$module$command.prototype.undo=function(a){a.clear();for(var b=0;b<this.erased.length;b++)a.write(this.erased[b],b,0)};EraseDisplayFull$$module$command.prototype.toString=function(){return"EraseDisplayFull"};
Object.defineProperties(EraseDisplayFull$$module$command.prototype,{keyframe:{configurable:!0,enumerable:!0,get:function(){return!0}}});var EraseDisplayStart$$module$command=function(){EraseDisplay$$module$command.call(this)};$jscomp.inherits(EraseDisplayStart$$module$command,EraseDisplay$$module$command);EraseDisplayStart$$module$command.parse=EraseDisplay$$module$command.parse;EraseDisplayStart$$module$command.prototype.params=function(){return[1]};
EraseDisplayStart$$module$command.prototype.apply=function(a){this.erased=a.clear([0,a.r]);this.erased.push(a.clear(a.r,[0,a.c])[0])};EraseDisplayStart$$module$command.prototype.undo=function(a){a.clear([0,a.r]);for(var b=0;b<this.erased.length;b++)a.write(this.erased[b],b,0)};EraseDisplayStart$$module$command.prototype.toString=function(){return"EraseDisplayStart"};var EraseDisplayEnd$$module$command=function(){EraseDisplay$$module$command.call(this)};
$jscomp.inherits(EraseDisplayEnd$$module$command,EraseDisplay$$module$command);EraseDisplayEnd$$module$command.parse=EraseDisplay$$module$command.parse;EraseDisplayEnd$$module$command.prototype.params=function(){return[0]};EraseDisplayEnd$$module$command.prototype.apply=function(a){this.erased=a.clear(a.r,[a.c]);this.erased.push.apply(this.erased,[].concat($jscomp.arrayFromIterable(a.clear([a.r]))))};
EraseDisplayEnd$$module$command.prototype.undo=function(a){a.clear([a.r+1]);a.clear(a.r,[a.c]);for(var b=0;b<this.erased.length;b++)a.write(this.erased[b],a.r+b,b?0:a.c)};EraseDisplayEnd$$module$command.prototype.toString=function(){return"EraseDisplayEnd"};var EraseInLine$$module$command=function(){BracketPrefix$$module$command.call(this);this.erased=[]};$jscomp.inherits(EraseInLine$$module$command,BracketPrefix$$module$command);EraseInLine$$module$command.parse=BracketPrefix$$module$command.parse;
EraseInLine$$module$command.prototype.suffix=function(){return"K"};var EraseInLineFull$$module$command=function(){EraseInLine$$module$command.call(this)};$jscomp.inherits(EraseInLineFull$$module$command,EraseInLine$$module$command);EraseInLineFull$$module$command.parse=EraseInLine$$module$command.parse;EraseInLineFull$$module$command.prototype.params=function(){return[2]};EraseInLineFull$$module$command.prototype.apply=function(a){this.erased=a.clear(a.r)[0]};
EraseInLineFull$$module$command.prototype.undo=function(a){a.clear(a.r);a.write(this.erased,a.r,0)};EraseInLineFull$$module$command.prototype.toString=function(){return"EraseInLineFull"};var EraseInLineStart$$module$command=function(){EraseInLine$$module$command.call(this)};$jscomp.inherits(EraseInLineStart$$module$command,EraseInLine$$module$command);EraseInLineStart$$module$command.parse=EraseInLine$$module$command.parse;EraseInLineStart$$module$command.prototype.params=function(){return[1]};
EraseInLineStart$$module$command.prototype.apply=function(a){this.erased=a.clear(a.r,[0,a.c])[0]};EraseInLineStart$$module$command.prototype.undo=function(a){a.write(this.erased,a.r,0)};EraseInLineStart$$module$command.prototype.toString=function(){return"EraseInLineStart"};var EraseInLineEnd$$module$command=function(){EraseInLine$$module$command.call(this)};$jscomp.inherits(EraseInLineEnd$$module$command,EraseInLine$$module$command);EraseInLineEnd$$module$command.parse=EraseInLine$$module$command.parse;
EraseInLineEnd$$module$command.prototype.params=function(){return[0]};EraseInLineEnd$$module$command.prototype.apply=function(a){this.erased=a.clear(a.r,[a.c])[0]};EraseInLineEnd$$module$command.prototype.undo=function(a){a.clear(a.r,[a.c]);a.write(this.erased,a.r,a.c)};EraseInLineEnd$$module$command.prototype.toString=function(){return"EraseInLineEnd"};function u16$$module$command(a){a>>>=0;return 0>a?0:65535<a?65535:a}
var AbstractMethod$$module$command=function(a){Error.call(this,void 0===a?"Method is abstract":a)};$jscomp.inherits(AbstractMethod$$module$command,Error);AbstractMethod$$module$command.captureStackTrace=Error.captureStackTrace;module$command.default=Command$$module$command;var module$frame={},Frame$$module$frame=function(){this.commands_=[];this.durationMs_=this.startMs_=0;this.keyframe_=!1;this.endCursor_=this.startCursor_=null};
Frame$$module$frame.parse=function(a){function b(b,n){for(;;)switch(c){case 0:l=new module$reader.default,g=new DataView(a),k=0;case 1:if(!(k<a.byteLength)){c=2;break}p=timeMs$$module$frame(g,k);h=g.getUint32(k+8,!0);f=k+12+h<a.byteLength?timeMs$$module$frame(g,k+12+h):Infinity;e=new Frame$$module$frame;e.startMs_=p;e.durationMs_=f-p;l.add(new DataView(a,k+12,h));for(d=void 0;d=module$command.default.parse(l);)d.keyframe&&(e.keyframe_=!0),e.commands_.push(d);c=3;return{value:e,done:!1};case 3:if(void 0===
n){c=4;break}c=-1;throw n;case 4:k+=12+h;c=1;break;case 2:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e,f,h,p,k,g,l,n={next:function(a){return b(a,void 0)},throw:function(a){return b(void 0,a)}};$jscomp.initSymbolIterator();n[Symbol.iterator]=function(){return this};return n};
Object.defineProperties(Frame$$module$frame.prototype,{startMs:{configurable:!0,enumerable:!0,get:function(){return this.startMs_}},durationMs:{configurable:!0,enumerable:!0,get:function(){return this.durationMs_},set:function(a){this.durationMs_=a}},keyframe:{configurable:!0,enumerable:!0,get:function(){return this.keyframe_}},commands:{configurable:!0,enumerable:!0,get:function(){return this.commands_}}});function timeMs$$module$frame(a,b){return 1E3*a.getUint32(b,!0)+a.getUint32(b+4,!0)/1E3}
module$frame.default=Frame$$module$frame;(function(){function a(a){function b(){for(;d>=c.length;){var a=e.next();if(a.done)return d=c.length,!1;c.push(a.value)}return!0}var c=[],d=0,e=module$frame.default.parse(a);return{commands:function(){return b()?c[d].commands:[]},time:function(){return new Date(c[d-!b()].startMs)},delayMs:function(){return b()?c[d].durationMs:Infinity},frame:function(){return d},setFrame:function(a){d=a},advance:function(){d++}}}function b(a,b){function c(a){a/=e;2E3<a&&(a=2E3);return a}function d(e){null==e&&(e=
1);m&&clearTimeout(m);for(m=null;0>e&&0<a.frame();)b.reverse(a.commands()),a.setFrame(a.frame()-1),e++;for(;0<e;)a.advance(),b.write(a.commands()),e--;r.onframe();q=0;f&&(e=c(a.delayMs()),m=setTimeout(d,e))}var e=1,f=!1,m=null,q=0,r={play:function(b){f!=b&&(f=b)&&(b=Math.max(c(a.delayMs())-q,0),m=setTimeout(d,b))},detach:function(){b.detach()},attach:function(){b.attach()},advance:d,speed:function(){return e},setSpeed:function(a){e=a},onframe:function(){}};return r}function c(a){var b=new module$state.default(a);
new module$reader.default;return{attach:function(){b.play()},detach:function(){b.pause()},write:function(a){a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c.value.apply(b)},reverse:function(a){for(var c=a.length-1;0<=c;c--)a[c].undo(b)}}}function d(a){var b=new XMLHttpRequest;b.open("get","http://cors.io/?u="+a);b.responseType="arraybuffer";b.onreadystatechange=function(){4==b.readyState&&e(b.response)};b.send()}function e(d){var e=c(document.getElementById("screen")),f=a(d);e.write(f.commands());
var g=b(f,e);g.onframe=function(){document.getElementById("time").textContent=f.frame()+": "+f.time()};document.getElementById("loadForm").style.display="none";document.getElementById("playForm").style.display="block";document.getElementById("next").addEventListener("click",function(){g.advance()});document.getElementById("prev").addEventListener("click",function(){g.advance(-1)});document.getElementById("next100").addEventListener("click",function(){g.detach();g.advance(100);g.attach()});document.getElementById("prev100").addEventListener("click",
function(){g.detach();g.advance(-100);g.attach()});var l=document.getElementById("play");l.addEventListener("click",function(){var a="play"==l.value;g.play(a);l.value=a?"pause":"play"});document.getElementById("speed").addEventListener("input",function(a){a=Math.pow(10,a.target.value);g.setSpeed(a);document.getElementById("speedDisplay").textContent=Math.floor(100*a)+"%"})}document.getElementById("files").addEventListener("change",function(a){a=a.target.files;var b=document.getElementById("selected");
b.innerHTML="<ul></ul>";for(var c=0,d;d=a[c];c++){var e=document.createElement("strong");e.textContent=d.name;var f=document.createElement("span");f.textContent=[" (",d.type||"n/a",") - ",d.size," bytes, last modified: ",d.lastModifiedDate?d.lastModifiedDate.toLocaleDateString():"n/a"].join("");d=document.createElement("li");d.appendChild(e);d.appendChild(f);b.firstChild.appendChild(d)}});document.getElementById("fetch").addEventListener("click",function(){var a=document.getElementById("files").files,
b=new FileReader;document.getElementById("selected").remove();b.onload=function(a){e(a.target.result)};b.readAsArrayBuffer(a[0])});var f=/\?url=(.*)/.exec(window.location.search);f&&d(f[1])})();
//# sourceMappingURL=jspbt.srcmap
